version: '3.9'
name: 'drones'

services:
  scene:
    image: test_ros
    container_name: drones
    entrypoint: ["/bin/bash", "-ci", "cd /ros_ws && catkin build && source devel/setup.bash && roslaunch mascot simulation.launch"]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
      - GUI=true
    ipc: host
    stdin_open: true
    tty: true
    networks:
      - general
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev

networks:
  general:
    attachable: true
    internal: false
    driver: bridge
